"""Update task and user models for habtica todo

Revision ID: 5ba96898646f
Revises: c360e36fce4e
Create Date: 2025-03-05 20:56:33.149601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba96898646f'
down_revision = 'c360e36fce4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='task_difficulty'), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('todo', 'habit', 'daily', name='task_type'), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('tasks_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hp')
        batch_op.drop_column('gold')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('completed_at')
        batch_op.drop_column('type')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
