"""Fix task model

Revision ID: 7faee4b006d7
Revises: 716bf3e0c5eb
Create Date: 2025-03-17 09:31:18.161867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faee4b006d7'
down_revision = '716bf3e0c5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('last_completed_at')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###
