"""Updated User models to add XP and level

Revision ID: c360e36fce4e
Revises: 3ac9f9b21696
Create Date: 2025-02-27 09:29:07.970762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c360e36fce4e'
down_revision = '3ac9f9b21696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
